// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBukNvmK1XP098XvUtOz52f_LJX6REf2uQ',
    appId: '1:1024656752190:web:7dbb2735204a0385ab5b6f',
    messagingSenderId: '1024656752190',
    projectId: 'todoo-5259c',
    authDomain: 'todoo-5259c.firebaseapp.com',
    storageBucket: 'todoo-5259c.appspot.com',
    measurementId: 'G-P35K3R0N44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBShM1kkmuns2Xt97XWgOHdTjva0W64qiU',
    appId: '1:1024656752190:android:e4c8f5b155026649ab5b6f',
    messagingSenderId: '1024656752190',
    projectId: 'todoo-5259c',
    storageBucket: 'todoo-5259c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsK6rK0MRF4sQRk9GS6br1zUirG_TIXQo',
    appId: '1:1024656752190:ios:ceab53038cb424e2ab5b6f',
    messagingSenderId: '1024656752190',
    projectId: 'todoo-5259c',
    storageBucket: 'todoo-5259c.appspot.com',
    iosClientId: '1024656752190-3hmts3en4e4ip51065fd757ek0mhorlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsK6rK0MRF4sQRk9GS6br1zUirG_TIXQo',
    appId: '1:1024656752190:ios:ceab53038cb424e2ab5b6f',
    messagingSenderId: '1024656752190',
    projectId: 'todoo-5259c',
    storageBucket: 'todoo-5259c.appspot.com',
    iosClientId: '1024656752190-3hmts3en4e4ip51065fd757ek0mhorlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );
}
